### ISSUE TITLE
question: custom include path using make file targets

### ISSUE THREAD

**Issue by stefanlendl** [zchee/deoplete-clang#31]
I am using a lot of different make file targets each independently installed libraries and so on.
Is it possible to add include paths for those to get proper full completion?
like YCM's https://github.com/Valloric/YouCompleteMe#c-family-semantic-completion
or Syntastic has a similar feature.

Thank you very much already!

**Comment by zchee** [comment]
@stefanlendl ah, sorry for late reply :(
Are you still interested it?

**Comment by HiPhish** [comment]
That sounds similar to `.clang_complete` file in clang_complete

> Each project can have a .clang_complete at its root, containing the compiler
options. This is useful if you're using some non-standard include paths or
need to specify particular architecture type, frameworks to use, path to
precompiled headers, precompiler definitions etc.
> 
> Note that as with other option sources, .clang_complete file is loaded and
parsed by the plugin only on buffer loading (or reloading, for example with
:edit! command). Thus no changes made to .clang_complete file after loading
source file into Vim's buffer will take effect until buffer will be closed and
opened again, reloaded or Vim is restarted.
> 
> Compiler options should go on individual lines (multiple options on one line
can work sometimes too, but since there are some not obvious conditions for
that, it's better to have one option per line).
> 
> Linking isn't performed during completion, so one doesn't need to specify any
of linker arguments in .clang_complete file. They will lead to completion
failure when using clang executable and will be completely ignored by
libclang.
> 
> Example .clang_complete file: >
>  -DDEBUG
>  -include ../config.h
>  -I../common
>  -I/usr/include/c++/4.5.3/
>  -I/usr/include/c++/4.5.3/x86_64-slackware-linux/

Deoplete-clang supports `g:deoplete#sources#clang#clang_complete_database`, which seems to do the same job, but it's global for all of Vim. We could work around this issue by having a project-local `.vimrc` with this plugin:
https://github.com/MarcWeber/vim-addon-local-vimrc
Neovim uses it to set various Vim settings like indentation so all developers have the same indentation settings when working on Neovim, regardless of their own Vim settings.

I haven't tried it myself, but I think this approach should be preferred over bolting on more features to deoplete-clang if it works.

**Comment by zchee** [comment]
@HiPhish Ah, you said meaning of this?
https://github.com/zchee/deoplete-clang/pull/24

**Comment by HiPhish** [comment]
@zchee Yes, that's what I meant, I didn't know it was already included.

**Comment by zchee** [comment]
@HiPhish Oh
Sorry, I had not yet written to the document :(
I will fix `README.md`!

**Comment by stefanlendl** [comment]
@zchee yes, great that's what I was looking for.
Thanks for the answer.

**Comment by zchee** [comment]
@stefanlendl Oh, ok! thanks :)
but maybe it's compile_commands flag are buggy because typo. I will fix it.

and, currently parse compile_commands.json is very slow :(
I tested neovim's `eval.c`, will be take a 1~3 sec on first show the complete list.
Now, I don't know it solved way(more performance).
Sorry.
