### ISSUE TITLE
How to enable completion for external libraries?

### ISSUE THREAD

**Issue by ambasta** [zchee/deoplete-clang#34]
Hi,

While deoplete-clang works wonders for stdlib, libraries such as boost/asio etc do not lead to code completion. How do I enable support for external libraries?

## Environment Information

 - OS: Linux(Gentoo)
 - Neovim version: 0.1.4

## init.vim

```
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_start_length = 1
let g:deoplete#sources#clang#libclang_path = "/usr/lib64/libclang.so"
let g:deoplete#sources#clang#clang_header = "/usr/lib64/clang/3.8.0/include/"
let g:deoplete#sources#clang#std#cpp = 'c++1z'
let g:deoplete#sources#clang#sort_algo = 'priority'
let g:deoplete#sources#clang#flags = [
    \ "-stdlib=libc++",
    \ ]
```

**Comment by zchee** [comment]
@ambasta Hi,

At first, I'm nerver written C and C++ \o/
So,

**Comment by ambasta** [comment]
`// Header names do not autocomplete //
#include <boost/graph/use_mpi.hpp>
#include <boost/graph/distributed/mpi_process_group.hpp>
#include <boost/graph/distributed/dijkstra_shortest_paths.hpp>
#include <boost/graph/distributed/adjacency_list.hpp>

#include <fstream>
#include <string>

#ifdef BOOST_NO_EXCEPTIONS
    void boost::throw_exception(std::exception const& exc) {
        std::cout << exc.what() << std::endl;
    }
#endif

using namespace boost;
using boost::graph::distributed::mpi_process_group;

// definitions such as adjacency_list etc don't always autocomplete
typedef adjacency_list<vecS, distributedS<mpi_process_group, vecS>, undirectedS, property<vertex_distance_t, float>, property<edge_weight_t, float> > Graph;

int main(int argc, char* argv[]) {
    return 0;
}
`

**Comment by Shougo** [comment]
I will test it later.

**Comment by Shougo** [comment]
I have tested this feature in your minimal init.vim.

* For header file completion: This feature is not implemented in deoplete-clang.
You should use `neoinclude` for it.

https://github.com/Shougo/neoinclude.vim

* for external library completion: It works, but it is very slow.  You must wait 5 seconds.

**Comment by ambasta** [comment]
@Shougo Any ideas on how I can speed this up?

**Comment by haifengkao** [comment]
YCM is very fast for external libraries as well

**Comment by zchee** [comment]
@haifengkao We know lol
We will do our best so that the equal speed.

**Comment by haifengkao** [comment]
@zchee I don't really understand why deoplete is slow for external libraries. libclang should work for external libraries (and fast). The only thing you need is to specify the header locations.

**Comment by zchee** [comment]
> I don't really understand why deoplete is slow for external libraries.
> libclang should work for external libraries (and fast).
> The only thing you need is to specify the header locations.

Yes, libclang is faster and de-facto library for parse C language.
`and fast` meaning of on YCM?
If so, Yes. YCM also uses libclang. But it's real libclang shared library.

**Maybe**(I do not much look at the YCM code) parse buffer, conversion AST to complete word or whatever, were executed C++ side.  Not through a Python.
We use `libclang-python3`. It's libclang binding for Python3, and performance is degraded because bypass a Python.
(If experience you have with the libclang-python and was not slow, please let me know)

I think If included small external library such as `dispatch.h`, it will fast.
But boost library seems large(I never used boost), very slow.
However, the slow cause might be a problem with the current deoplete-clang code, so we are during the validation now.

**Comment by zchee** [comment]
@haifengkao 
Ah, I'm overlooked.
> The only thing you need is to specify the header locations.

In other word? like `-L/usr/local/include/foo`?

**Comment by haifengkao** [comment]
@zchee YES.
